# Generated by Django 3.2.2 on 2022-05-10 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('information', models.TextField()),
                ('symptoms', models.TextField(default='abc')),
                ('causes', models.TextField(default='abc')),
                ('vulnerable', models.TextField(default='abc')),
                ('food_to_eat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_taken', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiverPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('total_bilirubin', models.CharField(max_length=5)),
                ('alkaline_phosphotase', models.CharField(max_length=5)),
                ('alamine_aminotransferase', models.CharField(max_length=5)),
                ('total_protiens', models.CharField(max_length=4)),
                ('albumin', models.CharField(max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeartPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('chest_pain_type', models.CharField(choices=[('Typical Angina', 'Typical Angina'), ('Atypical Angina', 'Atypical Angina'), ('Non-Anginal Pain', 'Non-Anginal Pain'), ('Asymptomatic', 'Asymptomatic')], default='Typical Angina', max_length=20)),
                ('resting_blood_pressure', models.CharField(max_length=3)),
                ('cholesterol', models.CharField(max_length=4)),
                ('fasting_blood_sugar', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('maximum_heart_rate_achieved', models.CharField(max_length=4)),
                ('exercise_induced_angina', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=14)),
                ('yoe', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('rating', models.CharField(max_length=5)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.disease')),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.CharField(max_length=3)),
                ('blood_pressure', models.CharField(max_length=3)),
                ('insulin', models.CharField(max_length=3)),
                ('body_mass_index', models.CharField(max_length=4)),
                ('age', models.CharField(max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
