# Generated by Django 3.2.2 on 2022-05-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartpatient',
            old_name='fasting_blood_sugar',
            new_name='fasting_blood_sugar_greater_than_120',
        ),
    ]
