# Generated by Django 3.2.2 on 2022-05-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_profile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.CreateModel(
            name='HeartPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('chest_pain_type', models.CharField(choices=[('Typical Angina', 'Typical Angina'), ('Atypical Angina', 'Atypical Angina'), ('Non-Anginal Pain', 'Non-Anginal Pain'), ('Asymptomatic', 'Asymptomatic')], default='Typical Angina', max_length=20)),
                ('resting_blood_pressure', models.CharField(max_length=3)),
                ('cholesterol', models.CharField(max_length=4)),
                ('fasting_blood_sugar', models.BooleanField(default=False)),
                ('maximum_heart_rate_achieved', models.CharField(max_length=4)),
                ('exercise_induced_angina', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
        ),
    ]
