# Generated by Django 3.2.2 on 2022-05-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_fasting_blood_sugar_heartpatient_fasting_blood_sugar_greater_than_120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='causes',
            field=models.TextField(default='causes.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='food_to_eat',
            field=models.TextField(default='green vegetables.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='information',
            field=models.TextField(default='information.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default='symptoms.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='vulnerable',
            field=models.TextField(default='vulnerable.'),
        ),
        migrations.AlterField(
            model_name='heartpatient',
            name='exercise_induced_angina',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='heartpatient',
            name='fasting_blood_sugar_greater_than_120',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
