# Generated by Django 3.2.2 on 2022-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220517_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(default='10AM - 11AM', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
