# Generated by Django 3.2.2 on 2022-05-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_heartpatient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartpatient',
            name='exercise_induced_angina',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
        migrations.AlterField(
            model_name='heartpatient',
            name='fasting_blood_sugar',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
    ]
