# Generated by Django 3.2.2 on 2022-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_diabetespatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartpatient',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
