# Generated by Django 3.2.2 on 2022-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_doctor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(default='10AM-3PM', max_length=20),
        ),
    ]
