# Generated by Django 3.2.2 on 2022-05-07 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_heartpatient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartpatient',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 7, 14, 12, 31, 28463, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
