# Generated by Django 3.2.2 on 2022-05-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_doctor_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
