# Generated by Django 3.2.2 on 2022-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_diabetespatient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='causes',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='disease',
            name='vulnerable',
            field=models.TextField(default='abc'),
        ),
    ]
