# Generated by Django 3.2.2 on 2022-05-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20220508_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('alkaline_phosphotase', models.CharField(max_length=5)),
                ('alamine_aminotransferase', models.CharField(max_length=5)),
                ('total_protiens', models.CharField(max_length=4)),
                ('albumin', models.CharField(max_length=4)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
        ),
    ]
