# Generated by Django 3.2.2 on 2022-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_bookdoctorappointment_time_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdoctorappointment',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
