# Generated by Django 3.2.2 on 2022-05-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_liverdisease'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiverDisease',
            new_name='LiverPatient',
        ),
    ]
