# Generated by Django 3.2.2 on 2022-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_bookdoctorappointment_time_of_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartpatient',
            old_name='cholesterol',
            new_name='serum_cholesterol',
        ),
        migrations.RemoveField(
            model_name='heartpatient',
            name='maximum_heart_rate_achieved',
        ),
        migrations.AddField(
            model_name='heartpatient',
            name='number_of_major_vessels_coloured_by_flouroscopy',
            field=models.CharField(default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='heartpatient',
            name='old_peak',
            field=models.CharField(default='1.1', max_length=5),
        ),
        migrations.AddField(
            model_name='heartpatient',
            name='resting_electrocardiographic_results',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Having ST-T', 'Having ST-T'), ('Hypertrophy', 'Hypertrophy')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='heartpatient',
            name='slope',
            field=models.CharField(default='2', max_length=5),
        ),
        migrations.AlterField(
            model_name='bookdoctorappointment',
            name='time_slot',
            field=models.CharField(default='10.AM', max_length=20),
        ),
    ]
