# Generated by Django 3.2.2 on 2022-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20220522_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='lifestyle_changes',
            field=models.TextField(default='Exercise and Meditate.'),
        ),
    ]
