# Generated by Django 3.2.2 on 2022-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_liverdisease_liverpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverpatient',
            name='total_bilirubin',
            field=models.CharField(default=0.4, max_length=5),
            preserve_default=False,
        ),
    ]
