# Generated by Django 4.0.4 on 2022-05-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_liverpatient_total_bilirubin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabetespatient',
            old_name='blood_pressuse',
            new_name='blood_pressure',
        ),
    ]
