# Generated by Django 4.0.4 on 2022-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_disease_lifestyle_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartpatient',
            name='number_of_major_vessels_coloured_by_flouroscopy',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='heartpatient',
            name='old_peak',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='heartpatient',
            name='slope',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
